stages:
  cleaning:
    cmd: python src/data/cleaning.py
    deps:
    - data/raw/dataset.csv
    - src/data/cleaning.py
    outs:
    - data/prep
  prepare:
    cmd: python src/data/prepare.py
    deps:
    - data/prep/dataset_cleaned.csv
    - src/data/prepare.py
    params:
    - prepare.seed
    - prepare.split
    outs:
    - data/train
    - data/test
  train:
    cmd: python src/model/train.py
    deps:
    - data/train/X_train.csv
    - data/train/y_train.csv
    - src/model/train.py