cleaning:
  input_path: data/raw/dataset.csv
  output_path: data/prep
  remove_duplicates: true
  remove_na: true

prepare:
  split: 0.20
  seed: 20170428

featurize:
  max_features: 100
  ngrams: 1

train:
  seed: 20170428
  n_est: 50
  min_split: 0.01

