# Nombre del paquete
package_name: modelo-popularidad

# Variable Objetivo
target: popularity

features:
  - duration_ms
  - explicit
  - danceability
  - energy
  - key
  - loudness
  - speechiness
  - acousticness
  - instrumentalness
  - liveness
  - valence
  - tempo
  - track_genre

# variables a mapear
qual_vars:
  - popularity

# 
categorical_vars:
  - mode
  - time_signature

# mapeo de variables
qual_mappings:
  No Popular: 0
  Baja: 1
  Media: 2
  Alta: 3


categorical_columns:
  - track_genre
  - key
  - mode
  - time_signature
feature_count: 18
high_cardinality_encoded:
  - track_genre
  - key
low_cardinality_encoded:
  - mode
  - time_signature
numeric_columns:
  - popularity
  - duration_ms
  - danceability
  - energy
  - loudness
  - speechiness
  - acousticness
  - instrumentalness
  - liveness
  - valence
  - tempo
target_column: popularity
